CREATE TABLE CAR(CAR_NO INT,CAR_NAME VARCHAR(30),CAR_PRICE INT,CAR_QUANTITY INT);
INSERT INTO CAR VALUES(1154,"TESLA",2300000,4),(2434,"BMW",210000,5),(9743,"AUDI",3200000,2),
						 (8645,"KIA",270000,3),(6123,"TATA",1500000,2);
                         
SELECT *FROM CAR;
SELECT COUNT(CAR_NAME),CAR_PRICE FROM CAR GROUP BY CAR_PRICE;

SELECT COUNT(CAR_NAME) AS CAR_COUNT,CAR_PRICE FROM CAR GROUP BY CAR_PRICE;

SELECT COUNT(CAR_NAME) FROM CAR GROUP BY CAR_PRICE HAVING  CAR_PRICE > 21000
UPDATE CAR SET CAR_PRICE = 2300000 WHERE CAR_PRICE = 210000;


CREATE TABLE VISIT(ENTRY_DATE DATE,PRICE INT ,DURATION INT);
INSERT INTO VISIT VALUES("2023-05-27",1000,20),
						("2023-05-01",1200,30),
                        ("2023-06-06",1000,20),
                        ("2023-07-012",2500,40),
                        ("2023-10-28",900,15);
                        
	SELECT *FROM VISIT;
    SELECT ENTRY_DATE,COUNT(*) FROM VISIT GROUP BY ENTRY_DATE;
    
    ----- EXTRACT KEYWORD EXAMPLES-----
    
    SELECT EXTRACT(YEAR FROM ENTRY_DATE) AS YEAR,
    EXTRACT(MONTH FROM ENTRY_DATE) AS MONTH,
    ----- ROUND FUNCTION ROUND OF THE DECIMAL POIUNTS UPTO 2 DECIMALS
    ROUND(AVG(PRICE),2) FROM VISIT GROUP BY EXTRACT(YEAR FROM ENTRY_DATE),EXTRACT(MONTH FROM ENTRY_DATE);

SELECT EXTRACT(YEAR FROM ENTRY_DATE) AS YEAR,
EXTRACT(MONTH FROM ENTRY_DATE) AS MONTH,
EXTRACT(DAY FROM ENTRY_DATE) AS DAY,
ROUND(AVG(PRICE),2) FROM VISIT 
GROUP BY EXTRACT(YEAR FROM ENTRY_DATE),EXTRACT(MONTH FROM ENTRY_DATE)
ORDER BY EXTRACT(YEAR FROM ENTRY_DATE),EXTRACT(MONTH FROM ENTRY_DATE);

SELECT EXTRACT(DAY FROM "2023-05-01");

SELECT *FROM CUSTOMER;
SELECT CITY ,COUNT(*) FROM CUSTOMER GROUP BY CITY;
SELECT CITY ,COUNT(*) FROM CUSTOMER GROUP BY CITY ORDER BY CITY;

CREATE TABLE EMPLOYEE(EMP_ID INT,NAME VARCHAR(20),AGE INT,COUNTRY VARCHAR(30));
INSERT INTO EMPLOYEE VALUES(100,"JYOTHI",50,"INDIA"),
							(101,"KASTURI",23,"US"),
                            (102,"PALLAVI",39,"US"),
                            (103,"VEDHA",40,"PAKISTHAN"),
                            (104,"RAVI",50,"INDIA");

SELECT *FROM EMPLOYEE;
SELECT COUNTRY,COUNT(COUNTRY) FROM EMPLOYEE GROUP BY COUNTRY HAVING COUNT(COUNTRY)>2;
SELECT COUNTRY,COUNT(COUNTRY) FROM EMPLOYEE GROUP BY COUNTRY;

SELECT COUNTRY,COUNT(COUNTRY) FROM EMPLOYEE GROUP BY COUNTRY HAVING MAX(AGE) >= 30;
SELECT COUNTRY,COUNT(COUNTRY) FROM EMPLOYEE GROUP BY COUNTRY HAVING MAX(AGE) <= 30;

CREATE TABLE MANAGER(ID INT,NAME VARCHAR(20),GENDER VARCHAR(20),AGE INT , SALARY INT);
INSERT INTO MANAGER VALUES(200,"JYOTHI","F",50,100000),
							(201,"KASTURI","F",23,150000),
                            (202,"PRATHAP","M",43,50000),
                            (203,"VEDHA","F",40,80000),
                            (204,"RAVI","M",50,150000);
INSERT INTO MANAGER VALUES(205,"SAI","M",43,80000),(206,"LUCKY","F",23,100000);
SELECT *FROM MANAGER;
SELECT NAME,SUM(SALARY) AS TOTSAL_SALARY FROM MANAGER GROUP BY NAME HAVING SUM(SALARY) > 100000 ORDER BY NAME;

SELECT AGE,COUNT(AGE) FROM MANAGER GROUP BY AGE HAVING COUNT(AGE) >=2;
SELECT GENDER,MAX(SALARY) FROM MANAGER GROUP BY GENDER HAVING MAX(SALARY) > 130000 ;
SELECT GENDER,MIN(SALARY) FROM MANAGER GROUP BY GENDER HAVING MIN(SALARY) < 130000 ;

DELIMITER //
CREATE PROCEDURE GetManagerInfo()
BEGIN
	SELECT *FROM MANAGER;
END //

CALL GetManagerInfo()

DELIMITER //
CREATE PROCEDURE GetManagerInfo()
   BEGIN
	SELECT *FROM MANAGER where age = 40;
   END //

CALL GetManagerInfO();

SELECT  NAME FROM MANAGER ORDER BY RAND() LIMIT 2;