import mysql.connector
mydb=mysql.connector.connect(host='localhost',user='root',password='Kasturi@2810',database='Inventory_Management')
cur=mydb.cursor()

t='CREATE TABLE MANUFACTURE(PRODUCT_ID INTEGER(20) NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,MANUFACTURED_COMPANY VARCHAR(30) NOT NULL,MANUFACTURED_DATE DATE NOT NULL,NEED_TO_BE_MANUFACTURED VARCHAR(30),NO_OF_ITEMS_MANUFACTURED INTEGER(20) NOT NULL,NO_OF_DEFECTIVE_ITEMS INTEGER(30) NOT NULL,MANUFACTURED_AMOUNT INTEGER(30) NOT NULL)'

t='CREATE TABLE GOODS (PRODUCT_ID INT NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,MANUFACTURED_COMPANY VARCHAR(30) NOT NULL,MANUFACTURED_DATE DATE NOT NULL,AVAILABLE_QUANTITY INT NOT NULL,COST_OF_ACH_ITEM INT NOT NULL)'

t='CREATE TABLE PURCHASE (PRODUCT_ID INT NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,PURCHASE_ID INT NOT NULL,PURCHASE_DATE DATE NOT NULL,PURCHASE_STORE VARCHAR(30) NOT NULL,PURCHASE_MODE VARCHAR(30) NOT NULL,PURCHASE_QUANTITY INT NOT NULL,PURCHASE_AMOUNT FLOAT NOT NULL,DEFECTIVE INT NOT NULL)'

t='CREATE TABLE SALES (PRODUCT_ID INT NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,SALES_QUANTITY INT NOT NULL,SALES_DATE DATE NOT NULL,SALES_AMOUNT INT NOT NULL,PROFIT_MARGIN INT NOT NULL);'
cur.execute(t)